/*
 * Created on 2025-08-02 ( 21:49:21 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DTO class for "Components"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ComponentsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer componentid;

    //--- OTHER DATA FIELDS 
    private String   componentname;

    //--- LINKS ( RELATIONSHIPS )
        @JsonIgnore
        private List<PartsDTO> listOfParts;

}
