/*
 * Created on 2025-07-24 ( 09:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * DTO class for "Cpu"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class CpuDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private Integer   coreCount;
    private BigDecimal   coreClock;
    private BigDecimal   boostClock;
    private Integer   tdp;
    private String   graphics;
    private Boolean   smt;

    //--- LINKS ( RELATIONSHIPS )
    @JsonManagedReference
    private PartsDTO parts;

}
