/*
 * Created on 2025-07-24 ( 09:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * DTO class for "Externalharddrive"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ExternalharddriveDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private String   type;
    private String   iface;
    private Integer   capacity;
    private BigDecimal   pricePerGb;
    private String   color;

    //--- LINKS ( RELATIONSHIPS )
    @JsonManagedReference
    private PartsDTO parts;

}
