/*
 * Created on 2025-07-24 ( 09:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * DTO class for "Monitor"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class MonitorDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private BigDecimal   screenSize;
    private String   resolution;
    private Integer   refreshRate;
    private Integer   responseTime;
    private String   panelType;
    private String   aspectRatio;

    //--- LINKS ( RELATIONSHIPS )
    @JsonManagedReference
    private PartsDTO parts;

}
