/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO class for "Mouse"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class MouseDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private String   trackingMethod;
    private String   connectionType;
    private Integer   maxDpi;
    private String   handOrientation;
    private String   color;

    //--- LINKS ( RELATIONSHIPS )
    @JsonManagedReference
    private PartsDTO parts;

}
