/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * DTO class for "Parts"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class PartsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private String   partname;
    private BigDecimal   partprice;
    private Integer   componentid;

    //--- LINKS ( RELATIONSHIPS )
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<KeyboardDTO> listOfKeyboard;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<OsDTO> listOfOs;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<CaseaccessoryDTO> listOfCaseaccessory;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<UpsDTO> listOfUps;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<CasefanDTO> listOfCasefan;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<MemoryDTO> listOfMemory;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<ExternalharddriveDTO> listOfExternalharddrive;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<MonitorDTO> listOfMonitor;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<HeadphonesDTO> listOfHeadphones;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<VideocardDTO> listOfVideocard;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<MouseDTO> listOfMouse;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<PowersupplyDTO> listOfPowersupply;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<PartunitDTO> listOfPartunit;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<SpeakersDTO> listOfSpeakers;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<SoundcardDTO> listOfSoundcard;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<FancontrollerDTO> listOfFancontroller;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<WirednetworkcardDTO> listOfWirednetworkcard;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<WirelessnetworkcardDTO> listOfWirelessnetworkcard;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<CpucoolerDTO> listOfCpucooler;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<CpuDTO> listOfCpu;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<MotherboardDTO> listOfMotherboard;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<WebcamDTO> listOfWebcam;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<OpticaldriveDTO> listOfOpticaldrive;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<ThermalpasteDTO> listOfThermalpaste;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<CasesDTO> listOfCases;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<InternalharddriveDTO> listOfInternalharddrive;
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private ComponentsDTO components;

}
