/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO class for "Partunit"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class PartunitDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;
    private Integer unitid;

    //--- OTHER DATA FIELDS 
    private String   measurename;

    //--- LINKS ( RELATIONSHIPS )
    @JsonManagedReference
    private UnitsDTO units;
    @JsonManagedReference
    private PartsDTO parts;

}
