/*
 * Created on 2025-07-25 ( 21:05:27 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DTO class for "Pcbuild"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class PcbuildDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer pcid;
    private Integer componentid;

    //--- OTHER DATA FIELDS 
    private Date   createdat;

    //--- LINKS ( RELATIONSHIPS )
        @JsonManagedReference
        private ComponentsDTO components;
        @JsonManagedReference
        private PcsDTO pcs;

}
