/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO class for "Pcbuild"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class PcbuildDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer pcid;
    private Integer componentid;
    private Integer accountid;

    //--- OTHER DATA FIELDS 

    //--- LINKS ( RELATIONSHIPS )
    @JsonManagedReference
    private AccountsDTO accounts;
    @JsonManagedReference
    private ComponentsDTO components;
    @JsonManagedReference
    private PcsDTO pcs;

}
