/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * DTO class for "Units"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class UnitsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Integer unitid;

    //--- OTHER DATA FIELDS 
    private String   unitcode;

    //--- LINKS ( RELATIONSHIPS )
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonBackReference
    private List<PartunitDTO> listOfPartunit;

}
