/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO class for "Videocard"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class VideocardDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private String   chipset;
    private Integer   memory;
    private Integer   coreClock;
    private Integer   boostClock;
    private String   color;
    private Integer   length;

    //--- LINKS ( RELATIONSHIPS )
    @JsonManagedReference
    private PartsDTO parts;

}
