/*
 * Created on 2025-07-25 ( 09:11:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.project.PCBuilder.persistence.entities.Accounts;
import com.project.PCBuilder.persistence.repositories.AccountsRepository;
import com.project.PCBuilder.rest.dto.AccountsDTO;
import com.project.PCBuilder.rest.services.commons.GenericService;

/**
 * REST service for entity "Accounts" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class AccountsService extends GenericService<Accounts, AccountsDTO> {

	private static final Logger logger = LoggerFactory.getLogger(AccountsService.class);

	private final AccountsRepository repository; // injected by constructor

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public AccountsService(AccountsRepository repository) {
		super(Accounts.class, AccountsDTO.class);
		this.repository = repository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Integer getEntityId(AccountsDTO dto) {
		return dto.getAccountid();
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<AccountsDTO> findAll() {
		logger.debug("findAll()");
		Iterable<Accounts> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param accountid 
	 * @return the entity or null if not found
	 */
	public AccountsDTO findById(Integer accountid) {
		Integer entityId = accountid;
		logger.debug("findById({})", entityId);
		Optional<Accounts> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param accountid 
	 * @param dto 
	 */
	public void save(Integer accountid, AccountsDTO dto) {
		Integer entityId = accountid;
		logger.debug("save({},{})", entityId, dto);
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setAccountid(accountid);
		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(AccountsDTO dto) {
		logger.debug("update({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param accountid 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Integer accountid, AccountsDTO dto) {
		Integer entityId = accountid;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		Optional<Accounts> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			Accounts entity = optionalEntity.get();
			// implement here the partial update
			// entity.setXxx(dto.getXxx());
			// etc ...
			repository.save(entity);
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(AccountsDTO dto) {
		logger.debug("create({})", dto);
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param accountid 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(Integer accountid) {
		Integer entityId = accountid;
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
/***
	public List<AccountsDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		// List<Accounts> list = repository.findByTitle(title);
		List<Accounts> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<AccountsDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		// List<Accounts> list = repository.findByTitle(title);
		List<Accounts> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}

	public List<AccountsDTO> findByTitleAndPrice(String title, BigDecimal price) {
		logger.debug("findByTitleAndPrice({}, {})", title, price);
		List<Accounts> list = repository.findByTitleContainingAndPrice(title, price);
		return entityListToDtoList(list);
	}
***/
}