/*
 * Created on 2025-07-25 ( 09:11:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.project.PCBuilder.persistence.entities.Partunit;
import com.project.PCBuilder.persistence.repositories.PartunitRepository;
import com.project.PCBuilder.rest.dto.PartunitDTO;
import com.project.PCBuilder.rest.services.commons.GenericService;
import com.project.PCBuilder.persistence.entities.PartunitId;

/**
 * REST service for entity "Partunit" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class PartunitService extends GenericService<Partunit, PartunitDTO> {

	private static final Logger logger = LoggerFactory.getLogger(PartunitService.class);

	private final PartunitRepository repository; // injected by constructor

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public PartunitService(PartunitRepository repository) {
		super(Partunit.class, PartunitDTO.class);
		this.repository = repository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private PartunitId getEntityId(PartunitDTO dto) {
		return new PartunitId(dto.getPartid(), dto.getUnitid());
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<PartunitDTO> findAll() {
		logger.debug("findAll()");
		Iterable<Partunit> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param partid 
	 * @param unitid 
	 * @return the entity or null if not found
	 */
	public PartunitDTO findById(Integer partid, Integer unitid) {
		PartunitId entityId = new PartunitId(partid, unitid);
		logger.debug("findById({})", entityId);
		Optional<Partunit> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param partid 
	 * @param unitid 
	 * @param dto 
	 */
	public void save(Integer partid, Integer unitid, PartunitDTO dto) {
		PartunitId entityId = new PartunitId(partid, unitid);
		logger.debug("save({},{})", entityId, dto);
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setPartid(partid);
		dto.setUnitid(unitid);
		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(PartunitDTO dto) {
		logger.debug("update({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param partid 
	 * @param unitid 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Integer partid, Integer unitid, PartunitDTO dto) {
		PartunitId entityId = new PartunitId(partid, unitid);
		logger.debug("partialUpdate({}, {})", entityId, dto);
		Optional<Partunit> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			Partunit entity = optionalEntity.get();
			// implement here the partial update
			// entity.setXxx(dto.getXxx());
			// etc ...
			repository.save(entity);
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(PartunitDTO dto) {
		logger.debug("create({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			return false; // already exists, not created
		} else {
			repository.save(dtoToEntity(dto));
			return true; // created
		}
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param partid 
	 * @param unitid 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(Integer partid, Integer unitid) {
		PartunitId entityId = new PartunitId(partid, unitid);
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
/***
	public List<PartunitDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		// List<Partunit> list = repository.findByTitle(title);
		List<Partunit> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<PartunitDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		// List<Partunit> list = repository.findByTitle(title);
		List<Partunit> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}

	public List<PartunitDTO> findByTitleAndPrice(String title, BigDecimal price) {
		logger.debug("findByTitleAndPrice({}, {})", title, price);
		List<Partunit> list = repository.findByTitleContainingAndPrice(title, price);
		return entityListToDtoList(list);
	}
***/
}