/*
 * Created on 2025-07-25 ( 09:11:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.project.PCBuilder.persistence.entities.Pcbuild;
import com.project.PCBuilder.persistence.repositories.PcbuildRepository;
import com.project.PCBuilder.rest.dto.PcbuildDTO;
import com.project.PCBuilder.rest.services.commons.GenericService;
import com.project.PCBuilder.persistence.entities.PcbuildId;

/**
 * REST service for entity "Pcbuild" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class PcbuildService extends GenericService<Pcbuild, PcbuildDTO> {

	private static final Logger logger = LoggerFactory.getLogger(PcbuildService.class);

	private final PcbuildRepository repository; // injected by constructor

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public PcbuildService(PcbuildRepository repository) {
		super(Pcbuild.class, PcbuildDTO.class);
		this.repository = repository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private PcbuildId getEntityId(PcbuildDTO dto) {
		return new PcbuildId(dto.getPcid(), dto.getComponentid(), dto.getAccountid());
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<PcbuildDTO> findAll() {
		logger.debug("findAll()");
		Iterable<Pcbuild> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param pcid 
	 * @param componentid 
	 * @param accountid 
	 * @return the entity or null if not found
	 */
	public PcbuildDTO findById(Integer pcid, Integer componentid, Integer accountid) {
		PcbuildId entityId = new PcbuildId(pcid, componentid, accountid);
		logger.debug("findById({})", entityId);
		Optional<Pcbuild> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param pcid 
	 * @param componentid 
	 * @param accountid 
	 * @param dto 
	 */
	public void save(Integer pcid, Integer componentid, Integer accountid, PcbuildDTO dto) {
		PcbuildId entityId = new PcbuildId(pcid, componentid, accountid);
		logger.debug("save({},{})", entityId, dto);
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setPcid(pcid);
		dto.setComponentid(componentid);
		dto.setAccountid(accountid);
		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(PcbuildDTO dto) {
		logger.debug("update({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param pcid 
	 * @param componentid 
	 * @param accountid 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Integer pcid, Integer componentid, Integer accountid, PcbuildDTO dto) {
		PcbuildId entityId = new PcbuildId(pcid, componentid, accountid);
		logger.debug("partialUpdate({}, {})", entityId, dto);
		Optional<Pcbuild> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			Pcbuild entity = optionalEntity.get();
			// implement here the partial update
			// entity.setXxx(dto.getXxx());
			// etc ...
			repository.save(entity);
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(PcbuildDTO dto) {
		logger.debug("create({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			return false; // already exists, not created
		} else {
			repository.save(dtoToEntity(dto));
			return true; // created
		}
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param pcid 
	 * @param componentid 
	 * @param accountid 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(Integer pcid, Integer componentid, Integer accountid) {
		PcbuildId entityId = new PcbuildId(pcid, componentid, accountid);
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
/***
	public List<PcbuildDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		// List<Pcbuild> list = repository.findByTitle(title);
		List<Pcbuild> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<PcbuildDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		// List<Pcbuild> list = repository.findByTitle(title);
		List<Pcbuild> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}

	public List<PcbuildDTO> findByTitleAndPrice(String title, BigDecimal price) {
		logger.debug("findByTitleAndPrice({}, {})", title, price);
		List<Pcbuild> list = repository.findByTitleContainingAndPrice(title, price);
		return entityListToDtoList(list);
	}
***/
}