
/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Composite primary key for entity "Partunit" ( stored in table "PartUnit" )
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PartunitId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    partid;
    private Integer    unitid;

}
