/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Parts"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Parts", schema="dbo", catalog="PCBuilder" )
public class Parts implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="PartName", nullable=false, length=256)
    private String           partname    ;

    @Column(name="PartPrice")
    private BigDecimal       partprice    ;

    @Column(name="ComponentID", nullable=false)
    private Integer          componentid    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="parts")
    private List<Keyboard> listOfKeyboard;

    @OneToMany(mappedBy="parts")
    private List<Os>   listOfOs;

    @OneToMany(mappedBy="parts")
    private List<Caseaccessory> listOfCaseaccessory;

    @OneToMany(mappedBy="parts")
    private List<Ups>  listOfUps;

    @OneToMany(mappedBy="parts")
    private List<Casefan> listOfCasefan;

    @OneToMany(mappedBy="parts")
    private List<Memory> listOfMemory;

    @OneToMany(mappedBy="parts")
    private List<Externalharddrive> listOfExternalharddrive;

    @OneToMany(mappedBy="parts")
    private List<Monitor> listOfMonitor;

    @OneToMany(mappedBy="parts")
    private List<Headphones> listOfHeadphones;

    @OneToMany(mappedBy="parts")
    private List<Videocard> listOfVideocard;

    @OneToMany(mappedBy="parts")
    private List<Mouse> listOfMouse;

    @OneToMany(mappedBy="parts")
    private List<Powersupply> listOfPowersupply;

    @OneToMany(mappedBy="parts")
    private List<Partunit> listOfPartunit;

    @OneToMany(mappedBy="parts")
    private List<Speakers> listOfSpeakers;

    @OneToMany(mappedBy="parts")
    private List<Soundcard> listOfSoundcard;

    @OneToMany(mappedBy="parts")
    private List<Fancontroller> listOfFancontroller;

    @OneToMany(mappedBy="parts")
    private List<Wirednetworkcard> listOfWirednetworkcard;

    @OneToMany(mappedBy="parts")
    private List<Wirelessnetworkcard> listOfWirelessnetworkcard;

    @OneToMany(mappedBy="parts")
    private List<Cpucooler> listOfCpucooler;

    @OneToMany(mappedBy="parts")
    private List<Cpu>  listOfCpu;

    @OneToMany(mappedBy="parts")
    private List<Motherboard> listOfMotherboard;

    @OneToMany(mappedBy="parts")
    private List<Webcam> listOfWebcam;

    @OneToMany(mappedBy="parts")
    private List<Opticaldrive> listOfOpticaldrive;

    @OneToMany(mappedBy="parts")
    private List<Thermalpaste> listOfThermalpaste;

    @OneToMany(mappedBy="parts")
    private List<Cases> listOfCases;

    @OneToMany(mappedBy="parts")
    private List<Internalharddrive> listOfInternalharddrive;

    @ManyToOne
    @JoinColumn(name="ComponentID", referencedColumnName="ComponentID", insertable=false, updatable=false)
    private Components components;

}