/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
  

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Partunit"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@IdClass(PartunitId.class)
@Table(name="PartUnit", schema="dbo", catalog="PCBuilder" )
public class Partunit implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    @Id
    @Column(name="UnitID", nullable=false)
    private Integer    unitid;

    //--- OTHER DATA FIELDS 
    @Column(name="MeasureName", length=256)
    private String           measurename    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="UnitID", referencedColumnName="UnitID", insertable=false, updatable=false)
    private Units      units;

    @ManyToOne
    @JoinColumn(name="PartID", referencedColumnName="PartID", insertable=false, updatable=false)
    private Parts      parts;

}