/*
 * Created on 2025-08-02 ( 21:32:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
  

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "Pcbuild"
 *
 * @author Telosys
 */

@Data
@NoArgsConstructor
@Entity
@Table(name="PCBuild", schema="dbo", catalog="PCBuilder" )
@IdClass(PcbuildId.class)
public class Pcbuild implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PCID", nullable=false)
    private Integer    pcid;

    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedAt")
    private Date             createdat    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="PCID", referencedColumnName="PCID", insertable=false, updatable=false)
    private Pcs        pcs;

    @ManyToOne
    @JoinColumn(name="PartID", referencedColumnName="PartID", insertable=false, updatable=false)
    private Parts      parts;

}