/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
  


package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Pcbuild"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@IdClass(PcbuildId.class)
@Table(name="PCBuild", schema="dbo", catalog="PCBuilder" )
public class Pcbuild implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PCID", nullable=false)
    private Integer    pcid;

    @Id
    @Column(name="ComponentID", nullable=false)
    private Integer    componentid;

    @Id
    @Column(name="AccountID", nullable=false)
    private Integer    accountid;

    //--- OTHER DATA FIELDS 
    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="AccountID", referencedColumnName="AccountID", insertable=false, updatable=false)
    private Accounts   accounts;

    @ManyToOne
    @JoinColumn(name="ComponentID", referencedColumnName="ComponentID", insertable=false, updatable=false)
    private Components components;

    @ManyToOne
    @JoinColumn(name="PCID", referencedColumnName="PCID", insertable=false, updatable=false)
    private Pcs        pcs;

}