/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Speakers"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Speakers", schema="dbo", catalog="PCBuilder" )
public class Speakers implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="configuration", length=50)
    private String           configuration    ;

    @Column(name="wattage")
    private Integer          wattage    ;

    @Column(name="frequency_response", length=50)
    private String           frequencyResponse    ;

    @Column(name="color", length=50)
    private String           color    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="PartID", referencedColumnName="PartID", insertable=false, updatable=false)
    private Parts      parts;

}