/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Units"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Units", schema="dbo", catalog="PCBuilder" )
public class Units implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="UnitID", nullable=false)
    private Integer    unitid;

    //--- OTHER DATA FIELDS 
    @Column(name="UnitCode", length=20)
    private String           unitcode    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="units")
    private List<Partunit> listOfPartunit;

}