/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Videocard"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="VideoCard", schema="dbo", catalog="PCBuilder" )
public class Videocard implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="chipset", length=50)
    private String           chipset    ;

    @Column(name="memory")
    private Integer          memory    ;

    @Column(name="core_clock")
    private Integer          coreClock    ;

    @Column(name="boost_clock")
    private Integer          boostClock    ;

    @Column(name="color", length=50)
    private String           color    ;

    @Column(name="length")
    private Integer          length    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="PartID", referencedColumnName="PartID", insertable=false, updatable=false)
    private Parts      parts;

}