/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Webcam"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Webcam", schema="dbo", catalog="PCBuilder" )
public class Webcam implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="resolutions", length=100)
    private String           resolutions    ;

    @Column(name="connection", length=50)
    private String           connection    ;

    @Column(name="focus_type", length=50)
    private String           focusType    ;

    @Column(name="os", length=100)
    private String           os    ;

    @Column(name="fov")
    private Integer          fov    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="PartID", referencedColumnName="PartID", insertable=false, updatable=false)
    private Parts      parts;

}