/*
 * Created on 2025-07-25 ( 21:14:29 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.persistence.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import com.project.PCBuilder.persistence.entities.Accounts;

/**
 * Spring Data JPA repository for entity "Accounts" <br>
 *
 * This repository extends JpaRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 *
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 *
 * @author Telosys
 *
 */
public interface AccountsRepository extends JpaRepository<Accounts, Integer> {

    // Insert specific finders here 

    //List<Accounts> findByXxx(String xxx);

    //List<Accounts> findByXxxStartingWith(String xxx);

    //List<Accounts> findByXxxContaining(String xxx);

    //List<Accounts> findByYyy(BigDecimal yyy);

    //List<Accounts> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
