/*
 * Created on 2025-08-02 ( 21:32:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.persistence.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import com.project.PCBuilder.persistence.entities.Pcbuild;
import com.project.PCBuilder.persistence.entities.PcbuildId;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
/**
 * Spring Data JPA repository for entity "Pcbuild" <br>
 *
 * This repository extends JpaRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 *
 * This repository can be extended by adding specific "finder" methods.<br>
 * For custom queries, follow Spring Data JPA derived query method conventions.
 *
 * @author Telosys
 */
public interface PcbuildRepository extends JpaRepository<Pcbuild, PcbuildId> {
	@Query("SELECT p FROM Pcbuild p WHERE p.pcid = :pcid")
	List<Pcbuild> findByPcid(@Param("pcid") Integer pcid);

    // -- Add your custom finder methods below --

    // Example: Find by a String field
    // List<Pcbuild> findByXxx(String xxx);

    // Example: Find by a field with LIKE behavior
    // List<Pcbuild> findByXxxContaining(String xxx);

    // Example: Find by a numerical field
    // List<Pcbuild> findByYyy(BigDecimal yyy);

    // Example: Find by foreign key (like PartID)
    // List<Pcbuild> findByPartID(Integer partID); // Use Optional<> or single result for OneToOne

}
