/*
 * Created on 2025-07-24 ( 09:27:37 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.persistence.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import com.project.PCBuilder.persistence.entities.Pcbuild;
import com.project.PCBuilder.persistence.entities.PcbuildId;

/**
 * Spring Data JPA repository for entity "Pcbuild" <br>
 *
 * This repository extends JpaRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 *
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 *
 * @author Telosys
 *
 */
public interface PcbuildRepository extends JpaRepository<Pcbuild, PcbuildId> {

    // Insert specific finders here 

    //List<Pcbuild> findByXxx(String xxx);

    //List<Pcbuild> findByXxxStartingWith(String xxx);

    //List<Pcbuild> findByXxxContaining(String xxx);

    //List<Pcbuild> findByYyy(BigDecimal yyy);

    //List<Pcbuild> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
